sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: deps="low"
    - php: 5.6
      env: SYMFONY_DI_VERSION=2.3.* PHPUNIT_VERSION=~3.7
    - php: 5.6
      env: SYMFONY_DI_VERSION=2.0.* SYMFONY_YAML_VERSION=2.7.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_DI_VERSION=2.1.* SYMFONY_YAML_VERSION=2.7.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_DI_VERSION=2.2.* SYMFONY_YAML_VERSION=2.7.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_DI_VERSION=2.3.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_DI_VERSION=2.4.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_DI_VERSION=2.6.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_DI_VERSION=2.7.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_DI_VERSION=2.8.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_DI_VERSION=3.0.* PHPUNIT_VERSION=~4.0
  allow_failures:
    - php: hhvm

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi
  - if [ "$SYMFONY_DI_VERSION" != "" ]; then composer require --no-update "symfony/dependency-injection:${SYMFONY_DI_VERSION}"; fi
  - if [ "$SYMFONY_YAML_VERSION" != "" ]; then composer require --no-update "symfony/yaml:${SYMFONY_YAML_VERSION}"; fi
  - if [ "$PHPUNIT_VERSION" != "" ]; then composer require --no-update "phpunit/phpunit:${PHPUNIT_VERSION}"; fi
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; fi
  - if [ "$deps" = "" ]; then composer install; fi

script: vendor/bin/phpunit

notifications:
  email: matthiasnoback@gmail.com

cache:
  directories:
    - $COMPOSER_CACHE_DIR
