language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION="2.1.*"
  - SYMFONY_VERSION="2.2.*"
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"

before_script:
before_script:
  - composer require symfony/dependency-injection:${SYMFONY_VERSION}
  - composer require symfony/config:${SYMFONY_VERSION}
  - composer install --dev

notifications:
  email: matthiasnoback@gmail.com